name: task_manager_firebase_09_09_25
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
