// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9z7eO6148zp8lZaDWYuliSx6ErFaQisk',
    appId: '1:577745966194:web:9c9add98934adb10751eeb',
    messagingSenderId: '577745966194',
    projectId: 'task-manager-app-dce95',
    authDomain: 'task-manager-app-dce95.firebaseapp.com',
    storageBucket: 'task-manager-app-dce95.firebasestorage.app',
    measurementId: 'G-0MMTN94Z4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs4nWHHFFx9zJCWqBoF0fCQo0on7vPneU',
    appId: '1:577745966194:android:a54b3d77579dec3e751eeb',
    messagingSenderId: '577745966194',
    projectId: 'task-manager-app-dce95',
    storageBucket: 'task-manager-app-dce95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6W6F4gw7Y7Qdx158Wd6p1-dyJe5N-CXY',
    appId: '1:577745966194:ios:154f50d575042ece751eeb',
    messagingSenderId: '577745966194',
    projectId: 'task-manager-app-dce95',
    storageBucket: 'task-manager-app-dce95.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase090925',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6W6F4gw7Y7Qdx158Wd6p1-dyJe5N-CXY',
    appId: '1:577745966194:ios:154f50d575042ece751eeb',
    messagingSenderId: '577745966194',
    projectId: 'task-manager-app-dce95',
    storageBucket: 'task-manager-app-dce95.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase090925',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9z7eO6148zp8lZaDWYuliSx6ErFaQisk',
    appId: '1:577745966194:web:559e905b9957c334751eeb',
    messagingSenderId: '577745966194',
    projectId: 'task-manager-app-dce95',
    authDomain: 'task-manager-app-dce95.firebaseapp.com',
    storageBucket: 'task-manager-app-dce95.firebasestorage.app',
    measurementId: 'G-WTH0CTSXPZ',
  );
}
